module.exports={
    devServer:{
        host:'localhost',
        port:8080,
        proxy:{
           '/api':{
            target:'https://www.fastmock.site/mock/3fb5b26bfa5f32d32ae6f74da6cd00a4/',
            changeOrigin:true,
            pathRewrite:{
                '/api':''
            }
           }
        }
    }
}